export const serviceCatalog = [
  {
    code: "svc-001",
    category: "Accounting & Bookkeeping",
    name: "Day-to-day accounting",
    description: "Voucher entry, ledger posting, and trial balance support.",
    basePrice: 30000,
    duration: "Monthly engagement",
    documents: ["Sales invoices", "Purchase bills", "Bank statements", "Previous books or data"],
    popular: false,
    icon: "book-open",
  },
  {
    code: "svc-002",
    category: "Accounting & Bookkeeping",
    name: "Preparation of final accounts",
    description: "Balance sheet and profit and loss account preparation.",
    basePrice: 20000,
    duration: "5-7 working days",
    documents: ["Ledger extracts", "Trial balance", "Bank statements", "Supporting vouchers"],
    popular: false,
    icon: "calculator",
  },
  {
    code: "svc-003",
    category: "Accounting & Bookkeeping",
    name: "Bank reconciliation & MIS reporting",
    description: "Bank reconciliation along with management reporting support.",
    basePrice: 10000,
    duration: "3-5 working days",
    documents: ["Bank statements", "Cash book", "Ledger data", "Reporting requirements"],
    popular: false,
    icon: "bar-chart",
  },
  {
    code: "svc-004",
    category: "Taxation (Direct Tax)",
    name: "Income Tax Return Filing (Individual, Firm, Company)",
    description: "Return filing support for individuals, firms, and companies.",
    basePrice: 1000,
    duration: "2-4 working days",
    documents: ["PAN card", "Aadhaar card", "Financial statements", "Tax documents"],
    popular: true,
    icon: "landmark",
  },
  {
    code: "svc-005",
    category: "Taxation (Direct Tax)",
    name: "Tax audit under section 44AB",
    description: "Tax audit compliance under section 44AB.",
    basePrice: 10000,
    duration: "7-10 working days",
    documents: ["Books of accounts", "Financial statements", "Audit schedules", "Tax working papers"],
    popular: false,
    icon: "shield-check",
  },
  {
    code: "svc-006",
    category: "Taxation (Direct Tax)",
    name: "TDS deduction, return filing & notice handling",
    description: "TDS calculation, return filing, and departmental notice support.",
    basePrice: 5000,
    duration: "3-5 working days",
    documents: ["TDS challans", "Deductee details", "Salary or vendor data", "Notice copies if any"],
    popular: false,
    icon: "file-text",
  },
  {
    code: "svc-007",
    category: "Taxation (Indirect Tax - GST)",
    name: "GST registration",
    description: "New GST registration support for eligible businesses.",
    basePrice: 3000,
    duration: "3-5 working days",
    documents: ["PAN card", "Aadhaar card", "Business address proof", "Bank statement"],
    popular: true,
    icon: "receipt",
  },
  {
    code: "svc-008",
    category: "Taxation (Indirect Tax - GST)",
    name: "Monthly/Quarterly/Annual return filing",
    description: "GST return filing support across regular filing cycles.",
    basePrice: 1000,
    duration: "1-3 working days",
    documents: ["Sales invoices", "Purchase register", "GSTR data", "Bank summary"],
    popular: true,
    icon: "file-text",
  },
  {
    code: "svc-009",
    category: "Taxation (Indirect Tax - GST)",
    name: "GST audit & ITC reconciliation",
    description: "GST audit support and input tax credit reconciliation.",
    basePrice: 5000,
    duration: "5-7 working days",
    documents: ["GSTR returns", "Books of accounts", "Purchase and sales data", "ITC workings"],
    popular: false,
    icon: "search-check",
  },
  {
    code: "svc-010",
    category: "Audit & Assurance",
    name: "Statutory audit (Companies Act audit)",
    description: "Statutory audit support under the Companies Act.",
    basePrice: 10000,
    duration: "7-10 working days",
    documents: ["Financial statements", "Books of accounts", "Supporting vouchers", "Management details"],
    popular: false,
    icon: "clipboard-check",
  },
  {
    code: "svc-011",
    category: "Audit & Assurance",
    name: "Internal audit",
    description: "Internal audit review and reporting support.",
    basePrice: 10000,
    duration: "5-7 working days",
    documents: ["Process notes", "Financial data", "Policy documents", "Supporting records"],
    popular: false,
    icon: "clipboard-list",
  },
  {
    code: "svc-012",
    category: "Audit & Assurance",
    name: "Stock audit / Bank audit",
    description: "Stock audit and bank audit support.",
    basePrice: 3000,
    duration: "3-5 working days",
    documents: ["Stock statements", "Inventory records", "Bank statements", "Loan documents"],
    popular: false,
    icon: "package-search",
  },
  {
    code: "svc-013",
    category: "Company Law & ROC Compliance",
    name: "Company registration (Pvt. Ltd., LLP, OPC, etc.)",
    description: "Incorporation support for companies, LLPs, and OPCs.",
    basePrice: 8000,
    duration: "7-10 working days",
    documents: ["Directors' KYC", "Address proof", "Business details", "NOC if applicable"],
    popular: true,
    icon: "building-2",
  },
  {
    code: "svc-014",
    category: "Company Law & ROC Compliance",
    name: "Annual filing (MGT-7, AOC-4)",
    description: "Annual ROC filing support for companies.",
    basePrice: 6000,
    duration: "5-7 working days",
    documents: ["Financial statements", "MGT-7 data", "AOC-4 data", "Board resolution"],
    popular: false,
    icon: "building-2",
  },
  {
    code: "svc-015",
    category: "Company Law & ROC Compliance",
    name: "Change in directors / registered office / capital",
    description: "ROC filing support for company changes and updates.",
    basePrice: 2000,
    duration: "3-5 working days",
    documents: ["MCA credentials", "Board resolution", "Supporting proofs", "Existing company documents"],
    popular: false,
    icon: "refresh-cw",
  },
  {
    code: "svc-016",
    category: "Business Registration & Advisory",
    name: "MSME (Udyam) registration",
    description: "Udyam registration support for eligible businesses.",
    basePrice: 1000,
    duration: "1-3 working days",
    documents: ["Aadhaar card", "PAN card", "Business details", "Contact details"],
    popular: true,
    icon: "store",
  },
  {
    code: "svc-017",
    category: "Business Registration & Advisory",
    name: "Shop & Establishment license",
    description: "Registration support for shop and establishment licenses.",
    basePrice: 8000,
    duration: "3-5 working days",
    documents: ["Business address proof", "Owner KYC", "Rent agreement or NOC", "Business details"],
    popular: false,
    icon: "badge-check",
  },
  {
    code: "svc-018",
    category: "Business Registration & Advisory",
    name: "Import Export Code (IEC)",
    description: "IEC registration support for import and export businesses.",
    basePrice: 8000,
    duration: "2-4 working days",
    documents: ["PAN card", "Address proof", "Bank certificate or cancelled cheque", "Business details"],
    popular: false,
    icon: "ship",
  },
  {
    code: "svc-019",
    category: "Payroll & HR Services",
    name: "Salary structuring & payroll management",
    description: "Payroll setup, salary structuring, and monthly processing support.",
    basePrice: 5000,
    duration: "Monthly engagement",
    documents: ["Employee master data", "Salary structure", "Attendance data", "Bank details"],
    popular: false,
    icon: "wallet",
  },
  {
    code: "svc-020",
    category: "Payroll & HR Services",
    name: "PF, ESI, PT registration & returns",
    description: "Payroll compliance registration and return filing support.",
    basePrice: 5000,
    duration: "3-5 working days",
    documents: ["Employee data", "Salary sheets", "Registration details", "Previous compliance records"],
    popular: false,
    icon: "users",
  },
  {
    code: "svc-021",
    category: "Payroll & HR Services",
    name: "Gratuity, Bonus & labour compliance",
    description: "Labour law compliance support for gratuity, bonus, and related matters.",
    basePrice: 5000,
    duration: "3-5 working days",
    documents: ["Employee records", "Salary registers", "Compliance history", "Policy documents"],
    popular: false,
    icon: "briefcase",
  },
  {
    code: "svc-022",
    category: "Financial Consultancy & Advisory",
    name: "Project report & CMA data preparation",
    description: "Project report and CMA data preparation support.",
    basePrice: 5000,
    duration: "5-7 working days",
    documents: ["Business plan", "Financial projections", "Existing financials", "Bank requirement details"],
    popular: false,
    icon: "file-bar-chart",
  },
  {
    code: "svc-023",
    category: "Financial Consultancy & Advisory",
    name: "Loan & finance documentation",
    description: "Support for business loan and finance documentation.",
    basePrice: 5000,
    duration: "5-7 working days",
    documents: ["KYC documents", "Financial statements", "Bank statements", "Loan application details"],
    popular: false,
    icon: "file-stack",
  },
  {
    code: "svc-024",
    category: "Financial Consultancy & Advisory",
    name: "Business valuation & budgeting",
    description: "Business valuation and budgeting support.",
    basePrice: 5000,
    duration: "5-7 working days",
    documents: ["Financial statements", "Revenue details", "Forecast assumptions", "Management inputs"],
    popular: false,
    icon: "line-chart",
  },
  {
    code: "svc-025",
    category: "Other Specialized Services",
    name: "Trust / NGO registration & audit",
    description: "Registration and audit support for trusts and NGOs.",
    basePrice: 5000,
    duration: "7-10 working days",
    documents: ["Founders' KYC", "Trust deed or governing document", "Address proof", "Objectives note"],
    popular: false,
    icon: "heart-handshake",
  },
  {
    code: "svc-026",
    category: "Other Specialized Services",
    name: "NRI taxation & FEMA compliance",
    description: "Taxation and FEMA compliance support for NRIs.",
    basePrice: 5000,
    duration: "5-7 working days",
    documents: ["Passport", "Foreign income details", "Indian income details", "Tax residency documents"],
    popular: false,
    icon: "globe",
  },
  {
    code: "svc-027",
    category: "Other Specialized Services",
    name: "Due diligence & management consulting",
    description: "Due diligence and advisory support for business decisions.",
    basePrice: 10000,
    duration: "7-10 working days",
    documents: ["Financial statements", "Legal documents", "Contracts", "Management information"],
    popular: false,
    icon: "scan-search",
  },
]
